server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver

    type=com:
      alibaba:
        druid:
          pool:
            DruidDataSource:



